### ISSUE TITLE
Error when running prepDE.py 

### ISSUE THREAD

**Issue by chickenHyop** [gpertea/stringtie#396]
Hi, 
I was trying to execute **prepDE.py** and I get the following error:

$ prepDE.py -i sample_gene.lst
Error: could not locate transcript ENST00000618889 entry for sample CASE2
Traceback (most recent call last):
  File "/data/leehyobin/Step0_RawFile/stringtie/stringtie/prepDE.py", line 284, in <module>
    geneDict.setdefault(geneIDs[i],{}) #gene_id
KeyError: 'ENST00000618889'

What can I do to solve this error? 
Do you have any idea why this error is occurring? 😥

**Comment by chickenHyop** [comment]
> Hi, I was trying to execute **prepDE.py** and I get the following error:
> 
> $ prepDE.py -i sample_gene.lst Error: could not locate transcript ENST00000618889 entry for sample CASE2 Traceback (most recent call last): File "/data/leehyobin/Step0_RawFile/stringtie/stringtie/prepDE.py", line 284, in geneDict.setdefault(geneIDs[i],{}) #gene_id KeyError: 'ENST00000618889'
> 
> What can I do to solve this error? Do you have any idea why this error is occurring? 😥
